<?php

$MYSQLHOST =$_ENV["$MYSQLHOST"];
$MYSQLUSER =$_ENV["$MYSQLUSER"];
$MYSQLPASSWORD=$_ENV["$MYSQLPASSWORD"];
$MYSQLDATABASE=$_ENV["$MYSQLDATABASE"];
$MYSQLPORT=$_ENV["$MYSQLPORT"];

$conexion = mysqli_connect($MYSQLHOST,$MYSQLUSER,$MYSQLPASSWORD,$MYSQLDATABASE,$MYSQLPORT);
